name: Deploy aws stack on git push
on:
  workflow_run:
    workflows: [ run_tests ]
    types:
      - completed
  push:
    branches: [master]
jobs:
  aws_cdk:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./cdk
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: cdk deploy
        uses: youyo/aws-cdk-github-actions@v2
        with:
            cdk_subcommand: 'deploy'
            cdk_stack: 'SmartGalleryStack'
            cdk_args: '--require-approval never'
            actions_comment: false
            cdk_version: 2.114.1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: eu-north-1
