name: Run tests for the CDK Stack
on:
  pull_request:
    branches: [api_s3]
  push:
    branches: [api_s3]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: install dependencies
        run: pip install -r lambda_code/requirements-dev.txt
      - name: Test handler
        working-directory: lambda_code/src/
        run: python3 -m unittest test_handler.TestHandler
      - name: Test Cdk Synth
        run: python3 -m unittest cdk/tests/cdk_tests/test_smart_gallery_stack.py
